name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm install

      - run: |
          git config user.name "Vasyl Dutchak" 
          git config user.email "vasuldutschak1993@gmail.com" 
          npm version ${{github.event.inputs.version}}
          git push origin master
          git push origin v${{github.event.inputs.version}}

      - run: npm run build

      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
